export interface QuestionnaireContentInterface {
  name: string;
  surname: string;
  patronymic: string;
  birthday: string;
  email: string;
  phone: string;
  sex: string;
  passport_series: string;
  passport_number: string;
  passport_org: string;
  passport_date: string;
  company: string;
  position: string;
  doc_type: string;
  oms: string;
  snils: string;
  adress_single: string;
  adress_reg_country: string;
  adress_reg_city: string;
  adress_reg_street: string;
  adress_reg_building: string;
  adress_reg_flat: string;
  adress_fact_country: string;
  adress_fact_city: string;
  adress_fact_street: string;
  adress_fact_building: string;
  adress_fact_flat: string;
}
